ecm/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),

]

ecm/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecm/search_app/urls.py
from django.urls import path
from . import views

app_name = 'search_app'

urlpatterns = [
    path('', views.SearchResult, name='SearchResult')

]

ecm/shop/urls.py
from django.urls import path
from . import views
# from . views import country_city_view
app_name='shop'

urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('/<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('/<slug:c_slug>/<slug:product_slug>/',views.proDetail,name='prodCatdetail'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('redin/',views.redin,name='redin'),
    # path('sub_form/',views.sub_form,name='subf_form'),
    path('success/',views.success,name='success')



]

ecm/cart/models.py
from django.db import models
from shop.models import Products
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)


    class Meta:
        db_table='Cart'
        ordering=['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product=models.ForeignKey(Products,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecm/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Products
from . models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=Products.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save(),
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)

        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Products,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1 :
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Products, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecm/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">



    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <script src="https://kit.fontawesome.com/16a04ba967.js" crossorigin="anonymous"></script>

    <title>{% block title%}{% endblock %}</title>
</head>
<body>
<div>
<!--  {% include 'header.html' %}-->
  {% include 'navbar.html' %}
  {% block body %}
  {% endblock %}
</div>
<!--{% include 'footer.html' %}-->
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>

<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

ecm/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

    {% if category %}
        {{category.description|truncatewords:155}}
    {% else %}
        Welcome to Shop-E, We have everything you want. Enjoy shopping with Us
    {% endif %}

{% endblock %}

{% block title %}

    {% if category %}
        {{category.name}} - Shop-E Online Store
    {% else %}
        Home
    {% endif %}

{% endblock %}

{% block body %}
{% if category %}
    <div>
      <div class="row my_row_class">
          <div class="mx-auto">
              <p><a href="{% url 'shop:allProdCat' %}">Our Product Collections</a></p>
          </div>
      </div>
    </div>
{% endif %}
<div class="mx_auto">
  {% if category %}
    <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
</div>
    <br>
<div>
  <h1 class="text-center my_title">{{category.name}}</h1>
  <p class="text-justify">{{category.description}}</p>
</div>
  {% else %}
<div>
  <img class="my_image my_image_padding" src="{% static 'img/register.jpg' %}" alt="Our Products" width="1510px">
</div>
    <br>
<!--<div>-->
<!--  <h1 class="text-center my_title">Our Product Collections</h1>-->
<!--  <p class="text-justify">SHOP-E Pvt Ltd (SHOP_E) is an online retailer and web service provider. The company provides products such as apparel, auto and industrial items, beauty and health products, electronics, grocery, games, jewelry, kids and baby products, music, sports goods, toys, and tools.</p>-->
<!--</div>-->
<!--{% endif %}-->
<!--<div class="container">-->
<!--    <div class="row mx_auto">-->
<!--        {% for product in products.object_list %}-->
<!--        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">-->
<!--            <div class="card text-center" style="min-width:18rem;">-->
<!--                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>-->
<!--                <div class="card-body">-->
<!--                    <h4>{{product.name}}</h4>-->
<!--                    <p>{{product.price}}</p>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--        {% endfor %}-->
<!--    </div>-->
<!--    <div class="mx_auto">-->
<!--        {% if products.paginator.num_pages > 1 %}-->

<!--        <hr>-->
<!--        <div class="text-center">-->
<!--            {% for pg in products.paginator.page_range %}-->
<!--            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>-->
<!--        {% endfor %}-->
<!--        </div>-->
<!--        {% endif %}-->
<!--    </div>-->
<!--    <br>-->
<!--</div>-->
<!--{% endblock %}-->

ecm/templates/footer.html
<div class="footer navbar-fixed-bottom  my_footer">
  <p class="text-center">&copy;shop-e Pvt ltd. All rights Reserved</p>
</div>

ecm/templates/header.html
{% load static %}
<header>
  <center>
    <a href="{% url 'shop:allProdCat' %}"><img src="{% static 'img/logo.png' %}" alt="logoimage" width="170px" height="200px"></a>
  </center>
</header>

ecm/templates/logerror.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>return to home</title>
   <link rel="stylesheet" href="{% static 'css/errormg.css' %}">
</head>
<body>

      <div class="center-container">
        <h1>Wrong Credentials. User dosen't Exist!</h1>
          <a href="{% url 'shop:login' %}"><button>Retry</button></a>        <a href="{% url 'shop:logout' %}"><button>Quit</button></a>
    </div>
</body>
</html>

ecm/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale:1.0">
    <title>login</title>
    <meta http-equiv="X-UA Compatible" content="IE=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>
<body style="display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
    background:#081b29;">
<div class="wrapper">
    <div class="form-box login">
        <h2 style="padding-left:50%;">Login</h2>
        <form  method="post">
            {% csrf_token %}
            <div class="input-box">
                <input type="text" name="username" required>
                <label>Username</label>
                <i class='bx bxs-user'></i>
            </div>
            <div class="input-box">
                <input type="password" name="password" required>
                <label>Password</label>
                <i class='bx bxs-lock-alt' ></i>
            </div>
            <button type="submit" class="lg-btn">Login</button>
            <div class="logreg-link">
                <p>Don't have an account?<a href="{% url 'shop:register' %}"class="register-link">Sign Up</a></p>
            </div>
        </form>
    </div>
</div>
</body>
</html>

ecm/templates/message.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>return to home</title>
   <link rel="stylesheet" href="{% static 'css/msgst.css' %}">
</head>
<body>

      <div class="center-container">
        <h1>Your purcahse was sucessfully completed. Return to home</h1>
          <a href="/"><button>home</button></a>                             <a href="{% url 'shop:logout' %}"><button>Logout</button></a>
    </div>
</body>
</html>

ecm/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
      <a class="navbar-brand" href="/" style="font-size:40px;padding-right:10px;padding-left:10px;color:blue;font-weight:600;">College Store</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item" style="font-size: 18px;font-color: white;font-weight:600;">
          <a class="nav-link" href="{% url 'shop:allProdCat' %}">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %}active{% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="true" style="font-size: 18px;font-color: white;font-weight:600;">
            Departments
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
             <div class="dropdown-content" style="width=auto";>
               <li style="font-size: 14px;font-color: white;font-weight:100;"><a class= "btn" href="https://en.wikipedia.org/wiki/Computer_science">Computer Science</a></li>
                 <li><hr class="dropdown-divider"></li>
               <ul style="font-size: 14px;font-color: white;font-weight:100;"><a class= "btn" href="https://en.wikipedia.org/wiki/Commerce">Commerce</a></ul>
                 <li><hr class="dropdown-divider"></li>
               <ul style="font-size: 14px;font-color: white;font-weight:100;"><a class= "btn" href="https://en.wikipedia.org/wiki/History">History</a></ul>
                 <li><hr class="dropdown-divider"></li>
               <ul style="font-size: 14px;font-color: white;font-weight:100;"><a class= "btn" href="https://en.wikipedia.org/wiki/Business_studies">Buisiness</a></ul>
             </div>

          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa-solid fa-cart-plus"></i>({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
       {% if user.is_authenticated %}
        <ul><h4>Hello {{user.username}}</h4></ul>
         <ul><a class="btn btn-danger" href="{% url 'shop:logout' %}"   >LogOut</a></ul>
        {% else %}
        <ul><a class="btn btn-dark" href="{% url 'shop:register' %}">REGISTER</a></ul>
        <ul><a class="btn btn-info" href="{% url 'shop:login' %}"   >LOGIN</a></ul>
        {% endif %}
      </form>
    </div>
  </div>
</nav>

ecm/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

        {{product.description|truncatewords:155}}

{% endblock %}

{% block title %}
    {% if category %}
        {{product.name}}-ShopE
    {% endif %}
{% endblock %}

{% block body %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p><a href="{% url 'shop:allProdCat' %}">HOME</a> | <a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}</p>
    </div>
</div>
<div class="container">
<br>
<div class="row">
    <div class=" col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{product.image.url}}" alt="{{product.name}}" width="350px" height="335px">

        </div>
    </div>

        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
            <h1 class="my_prod_title">{{product.name}}</h1>
            <p>${{product.price}}</p>
            <p class="my_title">Product Description</p>
            <p class="text-justify my_prod_text">{{product.description}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify my_prod_text" style="color:red;"><b>OUT OF STOCK</b></p>.
            {% else %}
            <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to cart</a>
            {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

ecm/templates/rederror.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>return to home</title>
   <link rel="stylesheet" href="{% static 'css/errormg.css' %}">
</head>
<body>

      <div class="center-container">
        <h1>Username Already in use.Try another Username.</h1>
          <a href="{% url 'shop:register' %}"><button>Retry</button></a>         <a href="{% url 'shop:logout' %}"><button>Quit</button></a>
    </div>
</body>
</html>

ecm/templates/redin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Redirect Link</title>
    <link rel="stylesheet" href="{% static 'css/newstyle.css' %}">
</head>
<body>
    <div class="center-container">
        <h1>Click To generate form</h1>
        <a href="{% url 'shop:redin' %}"><button>Continue</button></a>
    </div>
</body>
</html>

ecm/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale:1.0">
    <title>login</title>
    <meta http-equiv="X-UA Compatible" content="IE=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
</head>
<body style="display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
    background:#081b29;">
<div class="wrapper">
    <div class="form-box login">
        <h2 style="padding-left:50%;color:lime;font-weight:300%;">Register</h2>
        <form  method="post">
            {% csrf_token %}
            <div class="input-box">
                <input type="text" name="username" required>
                <label>Username</label>
                <i class='bx bxs-user'></i>
            </div>
            <div class="input-box">
                <input type="email" name="email" required>
                <label>Email</label>
                <i class='bx bxs-envelope'></i>
            </div>
            <div class="input-box">
                <input type="password" name="password" required>
                <label>Password</label>
                <i class='bx bxs-lock-alt' ></i>
            </div>
            <div class="input-box">
                <input type="password" name="confirm" required>
                <label>Confirm Password</label>
                <i class='bx bxs-lock-alt' ></i>
            </div>
            <button type="submit" class="lg-btn">Register</button>
        </form>
    </div>
</div>
</body>
</html>

ecm/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}


        We have varieties of Footwear Products From Original brands.


{% endblock %}

{% block title %}
    Search
{% endblock %}

{% block body %}
<div>
    <p class="text-center my_search_text">You have Searched for:<b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
            </div>
        </div>

        {% empty %}
        <div class="mx_auto">
            <p class="text-center my_search_text">0 Results Found</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

ecm/templates/sub_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale:1.0">
    <title>login</title>
    <meta http-equiv="X-UA Compatible" content="IE=edge">
<!-- <link rel="stylesheet" href="{% static 'css/formstyle.css' %}">&ndash;&gt;-->
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
<script>
var subjectObject = {
  "Study": {
    "Commerce": ["CA", "B.com", "M.com"],
    "Science": ["Bsc", "Msc", "Physics", "Chemistry"],
    "Arts": ["Economics", "Philosophy", "History", "Literature"]
  },
  "Enquiry": {
    "Purchase_Item": ["Studies", "Tutors", "Events"],
    "Contact_Us": ["E-mail", "Address", "PhoneNo"]
  }
}
window.onload = function() {
  var subjectSel = document.getElementById("subject");
  var topicSel = document.getElementById("topic");
  var chapterSel = document.getElementById("chapter");
  for (var x in subjectObject) {
    subjectSel.options[subjectSel.options.length] = new Option(x, x);
  }
  subjectSel.onchange = function() {
 //empty Chapters- and Topics- dropdowns
 chapterSel.length = 1;
 topicSel.length = 1;
    //display correct values
    for (var y in subjectObject[this.value]) {
      topicSel.options[topicSel.options.length] = new Option(y, y);
    }
  }
  topicSel.onchange = function() {
 //empty Chapters dropdown
 chapterSel.length = 1;
    //display correct values
    var z = subjectObject[subjectSel.value][this.value];
    for (var i = 0; i < z.length; i++) {
      chapterSel.options[chapterSel.options.length] = new Option(z[i], z[i]);
    }
  }
}
</script>
</head>
<body style="display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
    background:grey;">
<div class="wrapper">
    <div class="form-box login">
        <h2 style="padding-left:50%;color:lime;font-size:30px;font-weight:300%;">Form</h2>
        <form  method="post">
            {% csrf_token %}
            <label style="padding-left:30%;color:lime;font-size:18px;font-weight:300%;">Name</label>
            <div class="input-box" style="padding-left:30%;">
                <input style="width:250px;height:30px;" type="text" name="username" required>


            </div><br>
            <label style="padding-left:30%;color:lime;font-size:18px;font-weight:300%;">D.O.B</label>
            <div class="input-box" style="padding-left:30%;">
                <input type="date" name="date" required style="width:250px;height:30px;">


            </div><br>

            <label style="padding-left:30%;color:lime;font-size:18px;font-weight:300%;">Gender</label>
            <div class="input-box" style="padding-left:30%;">

                <input type="radio" name="gender" value="male">Male
                <input type="radio" name="gender" value="female">Female


            </div><br>

            <label style="padding-left:30%;color:lime;font-size:18px;font-weight:300%;">Email</label>
            <div class="input-box" style="padding-left:30%;">
                <input type="email" name="email" required style="width:250px;height:30px;">


            </div><br>


            <label style="padding-left:30%;color:lime;font-size:18px;font-weight:300%;">Password</label>
            <div class="input-box" style="padding-left:30%;">
                <input type="password" name="password" required style="width:250px;height:30px;">


            </div><br>


            <label style="padding-left:30%;color:lime;font-size:18px;font-weight:300%;">Phone Number</label>
            <div class="input-box" style="padding-left:30%;">
                <input type="number" name="number" required style="width:250px;height:30px;">


            </div><br>
            <label style="padding-left:30%;color:lime;font-size:18px;font-weight:300%;">Address</label>
            <div class="input-box" style="padding-left:30%;height:20%;">
                <input type="text" name="address" required style="width:250px;height:90px;">


            </div><br>
            <div class="input-box">
                <label style="padding-left:30%;color:lime;font-size:18px;font-weight:300%;">Purposes:</label>
                 <select name="subject" id="subject">
                    <option value="" selected="selected" style="width:250px;height:30px;">About</option>
                  </select>
                  <br><br>
                <label style="padding-left:30%;color:font-size:18px;color:lime;font-weight:300%;">Department:</label>
                 <select name="topic" id="topic">
                    <option value="" selected="selected" style="width:250px;height:30px;">-----------</option>
                  </select>
                  <br><br>
                 <label style="padding-left:30%;font-size:18px;color:lime;font-weight:300%;"> Courses:</label>
                <select name="chapter" id="chapter" >
                    <option value="" selected="selected" style="width:250px;height:30px;">----------</option>
                </select>
            </div><br><br>
            <label style="padding-left:30%;color:lime;font-size:18px;font-weight:300%;">Materials Required</label>
             <div class="input-box" style="padding-left:30%;">
                <input type="checkbox" name="materials" value="debit_notebook">Debit_Notebook
                 <input type="checkbox" name="materials" value="pen">Pen
                 <input type="checkbox" name="materials" value="exam_paper">Exam_Paper
                 <input type="checkbox" name="materials" value="record_book">Record_book

            </div><br><br><br>
        <center>
            <a href="{% url 'shop:success' %}"><button style="color:white;font-size:16px;font-weight:300;height:30px;width:100px;background:green" >Submit</button></a>
        </center>

        </form>
        <br>
        <center>
            <a href="{% url 'shop:logout' %}"><button style="color:white;font-size:16px;font-weight:300;height:30px;width:100px;background:red" >Logout</button></a>
        </center>
    </div>

</div>
</body>
</html>